### ISSUE TITLE
POOR FORM

### ISSUE THREAD

**Issue by andreasioan** [Mrmeguyme/timetable-clock#15]
https://github.com/Mrmeguyme/timetable-clock/blob/ca2cd2ab8ec8dafd07574bed7411333c47d32bbc/curPeriod.js#L289

Using multiple if/else if is cpu intensive. Change it to be a switch statement!

**Comment by Mrmeguyme** [comment]
yeah I think Will did this, I asked him about it too lol @Torca2001
