### ISSUE TITLE
Period not up to date

### ISSUE THREAD

**Issue by Darzee2244** [Mrmeguyme/timetable-clock#17]
Halfway through the year, my timetable changed and some of my classes have changed. The current code isn't right and it isn't displaying the correct subject or class. I just want to know if there is any way I can change the code or get it updated.

**Comment by Torca2001** [comment]
This is a known problem, it only affects changes to the second and fourth term as the program mistakenly only fetches the term 1 and term 3 timetables.
This is getting fixed in an update over the holidays.
Is it also possible to get your student number? to check.

**Comment by Mrmeguyme** [comment]
We're working on a new version of the application @Darzee2244. This will not be a problem in it, and it will have a lot of other fixes. It should be out by the start of next term.

**Comment by Mrmeguyme** [comment]
We've fixed the problem in the new version!
