### ISSUE TITLE
.exe randomly renames itself to "delete.exe"

### ISSUE THREAD

**Issue by Lv-L** [Mrmeguyme/timetable-clock#29]
???

**Comment by Torca2001** [comment]
Changing its name to Delete.exe is the program trying to run its auto update. If you have version 503 and below there was a problem with the auto updater, to fix please just download the latest version as the auto updater will constantly fail.
Download [5.2.0](https://github.com/Mrmeguyme/timetable-clock/releases/download/5.2.0/SchoolManager.exe)
Make sure the program is named SchoolManager.exe and everything should work after running.
